name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: blueye-robotics/blunux-onboard-sdk:blunux-3.3-x86_64
      volumes:
        - my_docker_volume:/volume_mount
    steps:
      - uses: actions/checkout@v2
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
